export const DEFAULT_PORT = 5003;
export const MIN_PORT = 1;
export const MAX_PORT = 65_535;

export const MILLISECONDS_PER_SECOND = 1_000;
export const SECONDS_PER_MINUTE = 60;

export const AUTH_RATE_LIMIT_WINDOW_MINUTES = 15;
export const AUTH_RATE_LIMIT_WINDOW_MS =
  AUTH_RATE_LIMIT_WINDOW_MINUTES * SECONDS_PER_MINUTE * MILLISECONDS_PER_SECOND;
export const AUTH_MAX_REQUESTS = 20;

export const API_RATE_LIMIT_WINDOW_MS = SECONDS_PER_MINUTE * MILLISECONDS_PER_SECOND;
export const API_MAX_REQUESTS = 120;

export const CACHE_DEFAULT_TTL_SECONDS = 60;
export const CACHE_CHECK_PERIOD_SECONDS = 120;
export const HTTP_SUCCESS_STATUS_MIN = 200;
export const HTTP_SUCCESS_STATUS_MAX_EXCLUSIVE = 300;

export const AGENT_QUERY_LIMIT = 100;
export const AGENT_CACHE_TTL_SECONDS = 60;
export const ADMIN_INBOX_DEFAULT_PAGE_SIZE = 25;
export const ADMIN_INBOX_MAX_PAGE_SIZE = 100;
export const ADMIN_SETTING_VALUE_MAX_LENGTH = 50;
export const CONTACT_NAME_MAX_LENGTH = 255;
export const CONTACT_EMAIL_MAX_LENGTH = 255;
export const CONTACT_MESSAGE_MIN_LENGTH = 10;
export const CONTACT_MESSAGE_MAX_LENGTH = 5_000;
export const REFRESH_TOKEN_BYTES = 48;

export const DEFAULT_CHUNK_SIZE = 800;
export const DEFAULT_CHUNK_OVERLAP = 150;
export const KNOWLEDGE_EMBEDDING_CONCURRENCY = 5;
export const KNOWLEDGE_DOCUMENT_QUERY_LIMIT = 100;
export const KNOWLEDGE_FILENAME_MAX_LENGTH = 255;
export const KNOWLEDGE_CONTENT_MAX_LENGTH = 10_000_000;